# Site settings
title: Parker Allan - Software Developer
description: Software Development Engineer in Test portfolio and blog
url: "https://parkerdev.net"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Default front matter
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Parker Allan"

# RSS Feed settings
feed:
  excerpt_only: false
  collections:
    posts:
      path: "/feed.xml"

# Build destination (optional - uncomment if you want to change from default _site)
# destination: ./build
